export interface HeaderColumnsType {
  columnIndex: string;
  columnName: string;
  columnRate?: number;
  width: string;
}

export const adaccountTableData: { nodes: any[] } = {
  nodes: [
    {
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        imp: 0,
        click: 0,
        ctr: 0,
        msg_send: 0,
        msg_open: 0,
        cost: 0,
      },
      id: 97135,
      userConfigs: null,
      adAccountId: 97135,
      depthActive: false,
    },
  ],
};

export const adaccountSubData = [
  {
    startDate: '2022-12-28',
    endDate: '2022-12-28',
    analysisItemMap: {},
    report: {
      imp: 0,
      click: 0,
      ctr: 0,
      msg_send: 0,
      msg_open: 0,
      cost: 0,
    },
    id: 97135,
    depth: 2,
  },
  {
    startDate: '2022-12-29',
    endDate: '2022-12-29',
    analysisItemMap: {},
    report: {
      imp: 0,
      click: 0,
      ctr: 0,
      msg_send: 0,
      msg_open: 0,
      cost: 0,
    },
    id: 97135,
    depth: 2,
  },
  {
    startDate: '2022-12-30',
    endDate: '2022-12-30',
    analysisItemMap: {},
    report: {
      imp: 0,
      click: 0,
      ctr: 0,
      msg_send: 0,
      msg_open: 0,
      cost: 0,
    },
    id: 97135,
    depth: 2,
  },
  {
    startDate: '2022-12-31',
    endDate: '2022-12-31',
    analysisItemMap: {},
    report: {
      imp: 0,
      click: 0,
      ctr: 0,
      msg_send: 0,
      msg_open: 0,
      cost: 0,
    },
    id: 97135,
    depth: 2,
  },
  {
    startDate: '2023-01-01',
    endDate: '2023-01-01',
    analysisItemMap: {},
    report: {
      imp: 0,
      click: 0,
      ctr: 0,
      msg_send: 0,
      msg_open: 0,
      cost: 0,
    },
    id: 97135,
    depth: 2,
  },
  {
    startDate: '2023-01-02',
    endDate: '2023-01-02',
    analysisItemMap: {},
    report: {
      imp: 0,
      click: 0,
      ctr: 0,
      msg_send: 0,
      msg_open: 0,
      cost: 0,
    },
    id: 97135,
    depth: 2,
  },
  {
    startDate: '2023-01-03',
    endDate: '2023-01-03',
    analysisItemMap: {},
    report: {
      imp: 0,
      click: 0,
      ctr: 0,
      msg_send: 0,
      msg_open: 0,
      cost: 0,
    },
    id: 97135,
    depth: 2,
  },
];

export const campaignTableData: { nodes: any[] } = {
  nodes: [
    {
      campaignId: 312555,
      campaignName: '1',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 312555,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 312557,
      campaignName: '1',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'VISITING',
      id: 312557,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 312560,
      campaignName: '11',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'VISITING',
      id: 312560,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 215370,
      campaignName: '1909_아비쥬의원',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 215370,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 911227,
      campaignName: '22222',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 911227,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 312468,
      campaignName: 'sdd',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 312468,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 312552,
      campaignName: 'ssdfs',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'CONVERSION',
      id: 312552,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 228976,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'VISITING',
      id: 228976,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 257994,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 257994,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
    {
      campaignId: 260279,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 260279,
      userConfigs: ['ON', 'DEL', 'OFF'],
      depthActive: false,
    },
  ],
};

export const campaignSubData = [
  {
    startDate: '2022-12-28',
    endDate: '2022-12-28',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
    },
    id: 312555,
    depth: 2,
  },
  {
    startDate: '2022-12-29',
    endDate: '2022-12-29',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
    },
    id: 312555,
    depth: 2,
  },
  {
    startDate: '2022-12-30',
    endDate: '2022-12-30',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
    },
    id: 312555,
    depth: 2,
  },
  {
    startDate: '2022-12-31',
    endDate: '2022-12-31',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
    },
    id: 312555,
    depth: 2,
  },
  {
    startDate: '2023-01-01',
    endDate: '2023-01-01',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
    },
    id: 312555,
    depth: 2,
  },
  {
    startDate: '2023-01-02',
    endDate: '2023-01-02',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
    },
    id: 312555,
    depth: 2,
  },
  {
    startDate: '2023-01-03',
    endDate: '2023-01-03',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
    },
    id: 312555,
    depth: 2,
  },
];

export const adGroupTableData: { nodes: any[] } = {
  nodes: [
    {
      campaignId: 312560,
      campaignName: '11',
      campaignUserConfig: 'DEL',
      adGroupId: 743915,
      adGroupName: '11',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'VISITING',
      id: 743915,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 215370,
      campaignName: '1909_아비쥬의원',
      campaignUserConfig: 'DEL',
      adGroupId: 522070,
      adGroupName: '썸네일피드',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 522070,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 911227,
      campaignName: '22222',
      campaignUserConfig: 'DEL',
      adGroupId: 2417535,
      adGroupName: '디스플레이_전환_202210261900',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 2417535,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 312468,
      campaignName: 'sdd',
      campaignUserConfig: 'DEL',
      adGroupId: 743710,
      adGroupName: 's',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 743710,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 257994,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      adGroupId: 619459,
      adGroupName: 'test',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 619459,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 262007,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      adGroupId: 628425,
      adGroupName: 'test',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 628425,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 298499,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      adGroupId: 712196,
      adGroupName: 'test',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'VISITING',
      id: 712196,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 260279,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      adGroupId: 624614,
      adGroupName: 'test1218',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'TALK_BIZ_BOARD',
      goal: 'VISITING',
      id: 624614,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 443256,
      campaignName: 'test',
      campaignUserConfig: 'DEL',
      adGroupId: 1120290,
      adGroupName: '디스플레이_전환_202012031523',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 1120290,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
    {
      campaignId: 913831,
      campaignName: '동영상_조회_202210311119',
      campaignUserConfig: 'DEL',
      adGroupId: 2425652,
      adGroupName: '동영상_조회_202210311119',
      adGroupUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'VIDEO',
      goal: 'VIEW',
      id: 2425652,
      userConfigs: ['OFF', 'DEL', 'ON'],
      depthActive: false,
    },
  ],
};

export const adGroupSubData = [
  {
    startDate: '2022-12-28',
    endDate: '2022-12-28',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 743915,
    depth: 2,
  },
  {
    startDate: '2022-12-29',
    endDate: '2022-12-29',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 743915,
    depth: 2,
  },
  {
    startDate: '2022-12-30',
    endDate: '2022-12-30',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 743915,
    depth: 2,
  },
  {
    startDate: '2022-12-31',
    endDate: '2022-12-31',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 743915,
    depth: 2,
  },
  {
    startDate: '2023-01-01',
    endDate: '2023-01-01',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 743915,
    depth: 2,
  },
  {
    startDate: '2023-01-02',
    endDate: '2023-01-02',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 743915,
    depth: 2,
  },
  {
    startDate: '2023-01-03',
    endDate: '2023-01-03',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 743915,
    depth: 2,
  },
];

export const creativeTableData: { nodes: any[] } = {
  nodes: [
    {
      campaignId: 215370,
      campaignName: '1909_아비쥬의원',
      campaignUserConfig: 'DEL',
      adGroupId: 522070,
      adGroupName: '썸네일피드',
      adGroupUserConfig: 'DEL',
      creativeId: 6751146,
      creativeName: '플러스친구',
      creativeUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 6751146,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 6751146,
      depthActive: false,
    },
    {
      campaignId: 205382,
      campaignName: '아비쥬 네일아트',
      campaignUserConfig: 'OFF',
      adGroupId: 497491,
      adGroupName: '1908_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 6486412,
      creativeName: '썸네일_플친추가',
      creativeUserConfig: 'ON',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 6486412,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 6486412,
      depthActive: false,
    },
    {
      campaignId: 205382,
      campaignName: '아비쥬 네일아트',
      campaignUserConfig: 'OFF',
      adGroupId: 522120,
      adGroupName: '1909_썸네일',
      adGroupUserConfig: 'DEL',
      creativeId: 6751342,
      creativeName: '플친추가',
      creativeUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 6751342,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 6751342,
      depthActive: false,
    },
    {
      campaignId: 205382,
      campaignName: '아비쥬 네일아트',
      campaignUserConfig: 'OFF',
      adGroupId: 526035,
      adGroupName: '1909_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 6789552,
      creativeName: '플친추가',
      creativeUserConfig: 'ON',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 6789552,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 6789552,
      depthActive: false,
    },
    {
      campaignId: 205382,
      campaignName: '아비쥬 네일아트',
      campaignUserConfig: 'OFF',
      adGroupId: 551224,
      adGroupName: '1910_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 7042004,
      creativeName: '사본-플친추가',
      creativeUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 7042004,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 7042004,
      depthActive: false,
    },
    {
      campaignId: 205382,
      campaignName: '아비쥬 네일아트',
      campaignUserConfig: 'OFF',
      adGroupId: 551224,
      adGroupName: '1910_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 7042072,
      creativeName: '사본1-플친추가',
      creativeUserConfig: 'ON',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 7042072,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 7042072,
      depthActive: false,
    },
    {
      campaignId: 205382,
      campaignName: '아비쥬 네일아트',
      campaignUserConfig: 'OFF',
      adGroupId: 583116,
      adGroupName: '1911_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 7337474,
      creativeName: '사본-사본1-플친추가',
      creativeUserConfig: 'ON',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 7337474,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 7337474,
      depthActive: false,
    },
    {
      campaignId: 200068,
      campaignName: '아비쥬의원',
      campaignUserConfig: 'ON',
      adGroupId: 484228,
      adGroupName: '1908_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 6384684,
      creativeName: '썸네',
      creativeUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 6384684,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 6384684,
      depthActive: false,
    },
    {
      campaignId: 200068,
      campaignName: '아비쥬의원',
      campaignUserConfig: 'ON',
      adGroupId: 484228,
      adGroupName: '1908_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 6351765,
      creativeName: '플러스친구_최종',
      creativeUserConfig: 'OFF',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 6351765,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 6351765,
      depthActive: false,
    },
    {
      campaignId: 200068,
      campaignName: '아비쥬의원',
      campaignUserConfig: 'ON',
      adGroupId: 484228,
      adGroupName: '1908_썸네일피드',
      adGroupUserConfig: 'OFF',
      creativeId: 6355956,
      creativeName: '플친',
      creativeUserConfig: 'DEL',
      startDate: '2022-12-28',
      endDate: '2023-01-03',
      analysisItemMap: {
        NONE: 'total',
      },
      report: {
        cost: 0,
        imp: 0,
        click: 0,
        ctr: 0,
        reach: 0,
        video_play_3s: 0,
        cost_per_imp: 0,
        cost_per_click: 0,
        cost_per_reach: 0,
        cost_per_video_play_3s: 0,
        msg_send: 0,
        msg_open: 0,
        msg_click: 0,
        msg_play: 0,
        cost_per_msg_send: 0,
        cost_per_msg_open: 0,
        cost_per_msg_click: 0,
        cost_per_msg_play: 0,
      },
      campaignType: 'DISPLAY',
      goal: 'CONVERSION',
      id: 6355956,
      userConfigs: ['OFF', 'DEL', 'ON'],
      representativeId: 6355956,
      depthActive: false,
    },
  ],
};

export const creativeSubData = [
  {
    startDate: '2022-12-28',
    endDate: '2022-12-28',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 6751146,
    depth: 2,
  },
  {
    startDate: '2022-12-29',
    endDate: '2022-12-29',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 6751146,
    depth: 2,
  },
  {
    startDate: '2022-12-30',
    endDate: '2022-12-30',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 6751146,
    depth: 2,
  },
  {
    startDate: '2022-12-31',
    endDate: '2022-12-31',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 6751146,
    depth: 2,
  },
  {
    startDate: '2023-01-01',
    endDate: '2023-01-01',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 6751146,
    depth: 2,
  },
  {
    startDate: '2023-01-02',
    endDate: '2023-01-02',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 6751146,
    depth: 2,
  },
  {
    startDate: '2023-01-03',
    endDate: '2023-01-03',
    analysisItemMap: {},
    report: {
      cost: 0,
      imp: 0,
      click: 0,
      ctr: 0,
      reach: 0,
      video_play_3s: 0,
      cost_per_imp: 0,
      cost_per_click: 0,
      cost_per_reach: 0,
      cost_per_video_play_3s: 0,
      msg_send: 0,
      msg_open: 0,
      msg_click: 0,
      msg_play: 0,
      cost_per_msg_send: 0,
      cost_per_msg_open: 0,
      cost_per_msg_click: 0,
      cost_per_msg_play: 0,
    },
    id: 6751146,
    depth: 2,
  },
];

export const responseAdAccountDataContent = [
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: null,
    campaignId: null,
    campaignName: null,
    campaignUserConfig: null,
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221228,
    endDate: 20230109,
    report: {
      cost: 1393448,
      impression: 1118680,
      click: 6287,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 124,
      cpc: 22163,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const responseAdAccountDailyDataContent = [
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: null,
    campaignId: null,
    campaignName: null,
    campaignUserConfig: null,
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230106,
    endDate: 20230106,
    report: {
      cost: 402646,
      impression: 326956,
      click: 1825,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 123,
      cpc: 22062,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: null,
    campaignId: null,
    campaignName: null,
    campaignUserConfig: null,
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230107,
    endDate: 20230107,
    report: {
      cost: 400307,
      impression: 316555,
      click: 1794,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 126,
      cpc: 22313,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: null,
    campaignId: null,
    campaignName: null,
    campaignUserConfig: null,
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230108,
    endDate: 20230108,
    report: {
      cost: 400565,
      impression: 320204,
      click: 1797,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 125,
      cpc: 22290,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: null,
    campaignId: null,
    campaignName: null,
    campaignUserConfig: null,
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230109,
    endDate: 20230109,
    report: {
      cost: 223775,
      impression: 181824,
      click: 1025,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 123,
      cpc: 21831,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const responseCampaignDataContent = [
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221129,
    endDate: 20230109,
    report: {
      cost: 1443924,
      impression: 1158499,
      click: 6516,
      reach: 3,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 1,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 1,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 124,
      cpc: 22159,
      reachRate: 48130800,
      videoPlayRate: 144392400,
    },
  },
  {
    id: 7,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 7,
    campaignName: '디스플레이_202212291137',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221129,
    endDate: 20230109,
    report: {
      cost: 303,
      impression: 6,
      click: 15,
      reach: 18,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 12,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 5,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 250,
      cpm: 5050,
      cpc: 2020,
      reachRate: 1683,
      videoPlayRate: 2525,
    },
  },
];

export const responseCampaignDailyDataContent = [
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221215,
    endDate: 20221215,
    report: {
      cost: 100,
      impression: 1,
      click: 1,
      reach: 3,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 1,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 1,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 100,
      cpm: 10000,
      cpc: 10000,
      reachRate: 3333,
      videoPlayRate: 10000,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230106,
    endDate: 20230106,
    report: {
      cost: 402646,
      impression: 326956,
      click: 1825,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 123,
      cpc: 22062,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230107,
    endDate: 20230107,
    report: {
      cost: 400307,
      impression: 316555,
      click: 1794,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 126,
      cpc: 22313,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230108,
    endDate: 20230108,
    report: {
      cost: 400565,
      impression: 320204,
      click: 1797,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 125,
      cpc: 22290,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230109,
    endDate: 20230109,
    report: {
      cost: 240306,
      impression: 194783,
      click: 1099,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 123,
      cpc: 21865,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const responseCampaignDailyDataContent2 = [
  {
    id: 7,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212291137',
    campaignUserConfig: 'ON',
    adGroupId: null,
    adGroupName: null,
    adGroupUserConfig: null,
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221215,
    endDate: 20221215,
    report: {
      cost: 303,
      impression: 6,
      click: 15,
      reach: 3,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 1,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 1,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 250,
      cpm: 5050,
      cpc: 2020,
      reachRate: 3333,
      videoPlayRate: 10000,
    },
  },
];

export const responseAdGroupDataContent = [
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221129,
    endDate: 20230109,
    report: {
      cost: 731160,
      impression: 610123,
      click: 3324,
      reach: 3,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 1,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 1,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 119,
      cpc: 21996,
      reachRate: 24372000,
      videoPlayRate: 73116000,
    },
  },
  {
    id: 2,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 2,
    adGroupName: '디스플레이_방문_202212150946_테스트2',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221129,
    endDate: 20230109,
    report: {
      cost: 729918,
      impression: 561476,
      click: 3266,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 130,
      cpc: 22348,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const responseAdGroupDailyDataContent = [
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221215,
    endDate: 20221215,
    report: {
      cost: 100,
      impression: 1,
      click: 1,
      reach: 3,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 1,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 1,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 100,
      cpm: 10000,
      cpc: 10000,
      reachRate: 3333,
      videoPlayRate: 10000,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230106,
    endDate: 20230106,
    report: {
      cost: 201960,
      impression: 172582,
      click: 918,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 117,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230107,
    endDate: 20230107,
    report: {
      cost: 199980,
      impression: 162457,
      click: 909,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 123,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230108,
    endDate: 20230108,
    report: {
      cost: 200200,
      impression: 166077,
      click: 910,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 120,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 1,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20230109,
    endDate: 20230109,
    report: {
      cost: 128920,
      impression: 109006,
      click: 586,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 118,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const responseAdGroupDailyDataContent2 = [
  {
    id: 2,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: null,
    creativeName: null,
    creativeUserConfig: null,
    representativeId: null,
    startDate: 20221215,
    endDate: 20221215,
    report: {
      cost: 729918,
      impression: 561476,
      click: 3266,
      reach: 3,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 1,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 1,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 130,
      cpc: 22348,
      reachRate: 3333,
      videoPlayRate: 10000,
    },
  },
];

export const responseCreativeDataContent = [
  {
    id: 2,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: 2,
    creativeName: '디스플레이_방문_202212150952_test',
    creativeUserConfig: 'ON',
    representativeId: 1,
    startDate: 20221129,
    endDate: 20230109,
    report: {
      cost: 125620,
      impression: 101556,
      click: 571,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 123,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 8,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: 8,
    creativeName: '소재테스트5',
    creativeUserConfig: 'ON',
    representativeId: 2,
    startDate: 20221129,
    endDate: 20230109,
    report: {
      cost: 126940,
      impression: 101547,
      click: 577,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 125,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const responseCreativeDailyDataContent = [
  {
    id: 2,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: 2,
    creativeName: '디스플레이_방문_202212150952_test',
    creativeUserConfig: 'ON',
    representativeId: 1,
    startDate: 20230106,
    endDate: 20230106,
    report: {
      cost: 31900,
      impression: 28683,
      click: 145,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 111,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 2,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: 2,
    creativeName: '디스플레이_방문_202212150952_test',
    creativeUserConfig: 'ON',
    representativeId: 1,
    startDate: 20230107,
    endDate: 20230107,
    report: {
      cost: 31900,
      impression: 26843,
      click: 145,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 118,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 2,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: 2,
    creativeName: '디스플레이_방문_202212150952_test',
    creativeUserConfig: 'ON',
    representativeId: 1,
    startDate: 20230108,
    endDate: 20230108,
    report: {
      cost: 34760,
      impression: 27724,
      click: 158,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 125,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
  {
    id: 2,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: 2,
    creativeName: '디스플레이_방문_202212150952_test',
    creativeUserConfig: 'ON',
    representativeId: 1,
    startDate: 20230109,
    endDate: 20230109,
    report: {
      cost: 27060,
      impression: 18306,
      click: 123,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 147,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const responseCreativeDailyDataContent2 = [
  {
    id: 8,
    adAccountId: 1,
    adAccountName: 'ac1',
    adTypeAndGoal: {
      adTypeName: 'DISPLAY',
      adGoalName: 'VISITING',
    },
    campaignId: 1,
    campaignName: '디스플레이_방문_202212150946',
    campaignUserConfig: 'ON',
    adGroupId: 1,
    adGroupName: '디스플레이_방문_202212150946_테스트1',
    adGroupUserConfig: 'ON',
    creativeId: 2,
    creativeName: '소재테스트5',
    creativeUserConfig: 'ON',
    representativeId: 1,
    startDate: 20230109,
    endDate: 20230109,
    report: {
      cost: 126940,
      impression: 101547,
      click: 577,
      reach: 0,
      videoAutoPlay: 0,
      videoTouches: 0,
      videoUnmute: 0,
      videoPlay3Seconds: 0,
      videoPlay5Seconds: 0,
      videoPlay10Seconds: 0,
      videoPlay15Seconds: 0,
      videoPlay30Seconds: 0,
      videoPlay60Seconds: 0,
      videoPlay25Percent: 0,
      videoPlay50Percent: 0,
      videoPlay75Percent: 0,
      videoPlay100Percent: 0,
      signUpDay1: 0,
      signUpDay7: 0,
      purchaseDay1: 0,
      purchaseDay7: 0,
      viewCartDay1: 0,
      viewCartDay7: 0,
      ctr: 0,
      cpm: 125,
      cpc: 22000,
      reachRate: 0,
      videoPlayRate: 0,
    },
  },
];

export const categoryItems: { id: number; label: string; value: string }[] = [
  { id: 0, label: '전체', value: 'ALL' },
  { id: 1, label: '광고계정', value: 'AD_ACCOUNT' },
  { id: 2, label: '캠페인', value: 'CAMPAIGN' },
  { id: 3, label: '광고그룹', value: 'AD_GROUP' },
  { id: 4, label: '소재', value: 'CREATIVE' },
];

export const statusItems: { id: number; label: string; value: string }[] = [
  { id: 1, label: 'ON', value: 'ON' },
  { id: 2, label: 'OFF', value: 'OFF' },
  { id: 3, label: '삭제', value: 'DEL' },
];

export const indicatorItems = [
  {
    groupId: 1,
    groupName: '비용 지표',
    columnItems: [{ groupId: 1, id: 1, label: '비용 지표', value: 'costIndicator' }],
  },
  {
    groupId: 2,
    groupName: '실적 지표',
    columnItems: [
      { groupId: 2, id: 2, label: '기본 지표', value: 'defaultIndicator' },
      // { groupId: 2, id: 3, label: '발송 지표', value: 'sendIndicator' },
    ],
  },
];

export const adaccountHeaderColumns: HeaderColumnsType[] = [
  {
    columnIndex: 'reportDate',
    columnName: '기간',
    width: '20%',
  },
  {
    columnIndex: 'impression',
    columnName: '노출수',
    width: '20%',
  },
  {
    columnIndex: 'click',
    columnName: '클릭수',
    width: '20%',
  },
  {
    columnIndex: 'ctr',
    columnName: '클릭률',
    width: '20%',
  },
  {
    columnIndex: 'cost',
    columnName: '비용',
    width: '20%',
  },
];

export const campaignHeaderColumns: HeaderColumnsType[] = [
  {
    columnIndex: 'adTypeAndGoal',
    columnName: '유형',
    width: '221px',
  },
  {
    columnIndex: 'campaignName',
    columnName: '캠페인',
    width: '221px',
  },
  {
    columnIndex: 'reportDate',
    columnName: '기간',
    width: '221px',
  },
];

export const adGroupHeaderColumns: HeaderColumnsType[] = [
  {
    columnIndex: 'adTypeAndGoal',
    columnName: '유형',
    width: '221px',
  },
  {
    columnIndex: 'campaignName',
    columnName: '캠페인',
    width: '221px',
  },
  {
    columnIndex: 'adGroupName',
    columnName: '광고그룹',
    width: '221px',
  },
  {
    columnIndex: 'reportDate',
    columnName: '기간',
    width: '221px',
  },
];

export const creativeHeaderColumns: HeaderColumnsType[] = [
  {
    columnIndex: 'adTypeAndGoal',
    columnName: '유형',
    width: '221px',
  },
  {
    columnIndex: 'campaignName',
    columnName: '캠페인',
    width: '221px',
  },
  {
    columnIndex: 'adGroupName',
    columnName: '광고그룹',
    width: '221px',
  },
  {
    columnIndex: 'creativeName',
    columnName: '소재',
    width: '221px',
  },
  {
    columnIndex: 'reportDate',
    columnName: '기간',
    width: '221px',
  },
];
export const costIndicatorHeaderColumns: HeaderColumnsType[] = [
  {
    columnIndex: 'cost',
    columnName: '비용',
    width: '109px',
  },
];
export const defaultIndicatorHeaderColumns: HeaderColumnsType[] = [
  {
    columnIndex: 'impression',
    columnName: '노출수',
    width: '109px',
  },
  {
    columnIndex: 'click',
    columnName: '클릭수',
    width: '109px',
  },
  {
    columnIndex: 'ctr',
    columnName: '클릭률',
    width: '109px',
  },
  {
    columnIndex: 'cpm',
    columnName: '노출당 비용',
    width: '109px',
  },
  {
    columnIndex: 'cpc',
    columnName: '클릭당 비용',
    width: '109px',
  },
];
