export interface Filter1DepthProps {
  id: number;
  filter_name: string;
  filter_index: string;
  has2depth: boolean;
  inpType?:
    | 'I' // 그냥 input
    | 'I&P(C)' // 콤마 input
    | 'S(ON/OFF)' // ON/OFF
    | 'S(CAMPAIGNSTATUS)' // 캠페인 운영 상태
    | 'S(ADGROUPSTATUS)' // 광고 운영 상태
    | 'S(CREATIVESTATUS)' // 소재 운영 상태
    | 'S(CREATIVEREVIEWSTATUS)' // 소재 심사 상태
    | 'S(CAMPAIGNTYPE)' // 캠페인 유형
    | 'S(CAMPAIGNGOAL)' // 캠페인 목표
    | 'S(CREATIVETYPE)' // 소재 유형
    | 'I&P(N)&S'; // input & select
}

export interface Filter2DepthProps {
  id: number;
  filter1_depth_id: number;
  filter_name: string;
  filter_index: string;
  has3depth: boolean;
  inpType?:
    | 'I' // 그냥 input
    | 'I&P(C)' // 콤마 input
    | 'S(ON/OFF)' // ON/OFF
    | 'S(CAMPAIGNSTATUS)' // 캠페인 운영 상태
    | 'S(ADGROUPSTATUS)' // 광고 운영 상태
    | 'S(CREATIVESTATUS)' // 소재 운영 상태
    | 'S(CREATIVEREVIEWSTATUS)' // 소재 심사 상태
    | 'S(CAMPAIGNTYPE)' // 캠페인 유형
    | 'S(CAMPAIGNGOAL)' // 캠페인 목표
    | 'S(CREATIVETYPE)' // 소재 유형
    | 'I&P(N)&S'; // input & select
}

export interface Filter3DepthProps {
  id: number;
  filter1_depth_id: number;
  filter2_depth_id: number;
  filter_name: string;
  filter_index: string;
  inpType?:
    | 'I' // 그냥 input
    | 'I&P(C)' // 콤마 input
    | 'S(ON/OFF)' // ON/OFF
    | 'S(CAMPAIGNSTATUS)' // 캠페인 운영 상태
    | 'S(ADGROUPSTATUS)' // 광고 운영 상태
    | 'S(CREATIVESTATUS)' // 소재 운영 상태
    | 'S(CREATIVEREVIEWSTATUS)' // 소재 심사 상태
    | 'S(CAMPAIGNTYPE)' // 캠페인 유형
    | 'S(CAMPAIGNGOAL)' // 캠페인 목표
    | 'S(CREATIVETYPE)' // 소재 유형
    | 'I&P(N)&S'; // input & select
  formatTitle: string;
}

export interface CheckboxListProps {
  id: number;
  inpId: string;
  inpLabel: string;
  inpValue: string;
  inpType: string;
}

export const filter1DepthItems: Array<Filter1DepthProps> = [
  { id: 1, filter_name: '이름/ID', filter_index: 'name', has2depth: true },
  { id: 2, filter_name: 'ON/OFF', filter_index: 'status', has2depth: true },
  { id: 3, filter_name: '운영 상태', filter_index: 'operationStatus', has2depth: true },
  {
    id: 4,
    filter_name: '소재 심사 상태',
    filter_index: 'creative.reviewStatuses',
    has2depth: false,
    inpType: 'S(CREATIVEREVIEWSTATUS)',
  },
  // { id: 5, filter_name: '캠페인 유형', filter_index: 'adTypeNames', has2depth: false, inpType: 'S(CAMPAIGNTYPE)' },
  // { id: 6, filter_name: '캠페인 목표', filter_index: 'adGoalNames', has2depth: false, inpType: 'S(CAMPAIGNGOAL)' },
  // { id: 7, filter_name: '소재 유형', filter_index: 'creative.formats', has2depth: false, inpType: 'S(CREATIVETYPE)' },
  { id: 8, filter_name: '캠페인 지표', filter_index: 'campaignIndicators', has2depth: true },
  { id: 9, filter_name: '광고그룹 지표', filter_index: 'adGroupIndicators', has2depth: true },
  { id: 10, filter_name: '소재 지표', filter_index: 'creativeIndicators', has2depth: true },
];

export const filter2DepthItems: Array<Filter2DepthProps> = [
  {
    id: 1,
    filter1_depth_id: 1,
    filter_name: '캠페인 이름',
    filter_index: 'campaign.name',
    has3depth: false,
    inpType: 'I',
  },
  {
    id: 2,
    filter1_depth_id: 1,
    filter_name: '광고그룹 이름',
    filter_index: 'adGroup.name',
    has3depth: false,
    inpType: 'I',
  },
  {
    id: 3,
    filter1_depth_id: 1,
    filter_name: '소재 이름',
    filter_index: 'creative.name',
    has3depth: false,
    inpType: 'I',
  },
  {
    id: 4,
    filter1_depth_id: 1,
    filter_name: '캠페인 ID',
    filter_index: 'campaign.ids',
    has3depth: false,
    inpType: 'I&P(C)',
  },
  {
    id: 5,
    filter1_depth_id: 1,
    filter_name: '광고그룹 ID',
    filter_index: 'adGroup.ids',
    has3depth: false,
    inpType: 'I&P(C)',
  },
  {
    id: 6,
    filter1_depth_id: 1,
    filter_name: '소재 ID',
    filter_index: 'creative.ids',
    has3depth: false,
    inpType: 'I&P(C)',
  },
  {
    id: 7,
    filter1_depth_id: 2,
    filter_name: '캠페인',
    filter_index: 'campaign.configs',
    has3depth: false,
    inpType: 'S(ON/OFF)',
  },
  {
    id: 8,
    filter1_depth_id: 2,
    filter_name: '광고그룹',
    filter_index: 'adGroup.configs',
    has3depth: false,
    inpType: 'S(ON/OFF)',
  },
  {
    id: 9,
    filter1_depth_id: 2,
    filter_name: '소재',
    filter_index: 'creative.configs',
    has3depth: false,
    inpType: 'S(ON/OFF)',
  },
  {
    id: 10,
    filter1_depth_id: 3,
    filter_name: '캠페인',
    filter_index: 'campaign.statuses',
    has3depth: false,
    inpType: 'S(CAMPAIGNSTATUS)',
  },
  {
    id: 11,
    filter1_depth_id: 3,
    filter_name: '광고그룹',
    filter_index: 'adGroup.statuses',
    has3depth: false,
    inpType: 'S(ADGROUPSTATUS)',
  },
  {
    id: 12,
    filter1_depth_id: 3,
    filter_name: '소재',
    filter_index: 'creative.statuses',
    has3depth: false,
    inpType: 'S(CREATIVESTATUS)',
  },
  {
    id: 13,
    filter1_depth_id: 8,
    filter_name: '비용 지표',
    filter_index: 'campaignCostIndicators',
    has3depth: true,
  },
  {
    id: 14,
    filter1_depth_id: 8,
    filter_name: '기본 지표',
    filter_index: 'campaignDefaultIndicators',
    has3depth: true,
  },
  // {
  //   id: 15,
  //   filter1_depth_id: 8,
  //   filter_name: 'SDK 전환 지표',
  //   filter_index: 'campaignSdkIndicators',
  //   has3depth: true,
  // },
  {
    id: 16,
    filter1_depth_id: 9,
    filter_name: '비용 지표',
    filter_index: 'adGroupCostIndicators',
    has3depth: true,
  },
  {
    id: 17,
    filter1_depth_id: 9,
    filter_name: '기본 지표',
    filter_index: 'adGroupDefaultIndicators',
    has3depth: true,
  },
  // {
  //   id: 18,
  //   filter1_depth_id: 9,
  //   filter_name: 'SDK 전환 지표',
  //   filter_index: 'adGroupSdkIndicators',
  //   has3depth: true,
  // },
  {
    id: 19,
    filter1_depth_id: 10,
    filter_name: '비용 지표',
    filter_index: 'creativeCostIndicators',
    has3depth: true,
  },
  {
    id: 20,
    filter1_depth_id: 10,
    filter_name: '기본 지표',
    filter_index: 'creativeDefaultIndicators',
    has3depth: true,
  },
  // {
  //   id: 21,
  //   filter1_depth_id: 10,
  //   filter_name: 'SDK 전환 지표',
  //   filter_index: 'creativeSdkIndicators',
  //   has3depth: true,
  // },
];

export const filter3DepthItems: Array<Filter3DepthProps> = [
  {
    id: 1,
    filter1_depth_id: 8,
    filter2_depth_id: 13,
    filter_name: '비용',
    filter_index: 'campaign.campaign_indicator.COST',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 비용',
  },
  {
    id: 2,
    filter1_depth_id: 8,
    filter2_depth_id: 14,
    filter_name: '노출수',
    filter_index: 'campaign.campaign_indicator.IMPRESSION',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 노출수',
  },
  {
    id: 3,
    filter1_depth_id: 8,
    filter2_depth_id: 14,
    filter_name: '클릭수',
    filter_index: 'campaign.campaign_indicator.CLICK',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 클릭수',
  },
  {
    id: 4,
    filter1_depth_id: 8,
    filter2_depth_id: 14,
    filter_name: '클릭률',
    filter_index: 'campaign.campaign_indicator.CTR',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 클릭률',
  },
  // {
  //   id: 5,
  //   filter1_depth_id: 8,
  //   filter2_depth_id: 14,
  //   filter_name: '도달수',
  //   filter_index: 'campaign.campaign_indicator.REACH',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '캠페인 도달수',
  // },
  // {
  //   id: 6,
  //   filter1_depth_id: 8,
  //   filter2_depth_id: 14,
  //   filter_name: '재생수',
  //   filter_index: 'campaign.campaign_indicator.VIDEO_PLAY_3_SECONDS',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '캠페인 재생수',
  // },
  {
    id: 7,
    filter1_depth_id: 8,
    filter2_depth_id: 14,
    filter_name: '노출당 비용',
    filter_index: 'campaign.campaign_indicator.CPM',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 노출당 비용',
  },
  {
    id: 8,
    filter1_depth_id: 8,
    filter2_depth_id: 14,
    filter_name: '클릭당 비용',
    filter_index: 'campaign.campaign_indicator.CPC',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 클릭당 비용',
  },
  // {
  //   id: 9,
  //   filter1_depth_id: 8,
  //   filter2_depth_id: 14,
  //   filter_name: '도달당 비용',
  //   filter_index: 'campaign.campaign_indicator.REACH_RATE',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '캠페인 도달당 비용',
  // },
  // {
  //   id: 10,
  //   filter1_depth_id: 8,
  //   filter2_depth_id: 14,
  //   filter_name: '재생당 비용',
  //   filter_index: 'campaign.campaign_indicator.VIDEO_PLAY_RATE',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '캠페인 재생당 비용',
  // },
  {
    id: 11,
    filter1_depth_id: 8,
    filter2_depth_id: 15,
    filter_name: '회원가입 (1일)',
    filter_index: 'campaign.campaign_indicator.SIGNUP_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 회원가입 (1일)',
  },
  {
    id: 12,
    filter1_depth_id: 8,
    filter2_depth_id: 15,
    filter_name: '장바구니 보기 (1일)',
    filter_index: 'campaign.campaign_indicator.VIEW_CART_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 장바구니 보기 (1일)',
  },
  {
    id: 13,
    filter1_depth_id: 8,
    filter2_depth_id: 15,
    filter_name: '구매 (1일)',
    filter_index: 'campaign.campaign_indicator.PURCHASE_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 구매 (1일)',
  },
  {
    id: 14,
    filter1_depth_id: 8,
    filter2_depth_id: 15,
    filter_name: '회원가입 (7일)',
    filter_index: 'campaign.campaign_indicator.SIGNUP_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 회원가입 (7일)',
  },
  {
    id: 15,
    filter1_depth_id: 8,
    filter2_depth_id: 15,
    filter_name: '장바구니 보기 (7일)',
    filter_index: 'campaign.campaign_indicator.VIEW_CART_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 장바구니 보기 (7일)',
  },
  {
    id: 16,
    filter1_depth_id: 8,
    filter2_depth_id: 15,
    filter_name: '구매 (7일)',
    filter_index: 'campaign.campaign_indicator.PURCHASE_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '캠페인 구매 (7일)',
  },
  {
    id: 17,
    filter1_depth_id: 9,
    filter2_depth_id: 16,
    filter_name: '비용',
    filter_index: 'adGroup.adGroup_indicator.COST',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 비용',
  },
  {
    id: 18,
    filter1_depth_id: 9,
    filter2_depth_id: 17,
    filter_name: '노출수',
    filter_index: 'adGroup.adGroup_indicator.IMPRESSION',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 노출수',
  },
  {
    id: 19,
    filter1_depth_id: 9,
    filter2_depth_id: 17,
    filter_name: '클릭수',
    filter_index: 'adGroup.adGroup_indicator.CLICK',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 클릭수',
  },
  {
    id: 20,
    filter1_depth_id: 9,
    filter2_depth_id: 17,
    filter_name: '클릭률',
    filter_index: 'adGroup.adGroup_indicator.CTR',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 클릭률',
  },
  // {
  //   id: 21,
  //   filter1_depth_id: 9,
  //   filter2_depth_id: 17,
  //   filter_name: '도달수',
  //   filter_index: 'adGroup.adGroup_indicator.REACH',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '광고그룹 도달수',
  // },
  // {
  //   id: 22,
  //   filter1_depth_id: 9,
  //   filter2_depth_id: 17,
  //   filter_name: '재생수',
  //   filter_index: 'adGroup.adGroup_indicator.VIDEO_PLAY_3_SECONDS',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '광고그룹 재생수',
  // },
  {
    id: 23,
    filter1_depth_id: 9,
    filter2_depth_id: 17,
    filter_name: '노출당 비용',
    filter_index: 'adGroup.adGroup_indicator.CPM',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 노출당 비용',
  },
  {
    id: 24,
    filter1_depth_id: 9,
    filter2_depth_id: 17,
    filter_name: '클릭당 비용',
    filter_index: 'adGroup.adGroup_indicator.CPC',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 클릭당 비용',
  },
  // {
  //   id: 25,
  //   filter1_depth_id: 9,
  //   filter2_depth_id: 17,
  //   filter_name: '도달당 비용',
  //   filter_index: 'adGroup.adGroup_indicator.REACH_RATE',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '광고그룹 도달당 비용',
  // },
  // {
  //   id: 26,
  //   filter1_depth_id: 9,
  //   filter2_depth_id: 17,
  //   filter_name: '재생당 비용',
  //   filter_index: 'adGroup.adGroup_indicator.VIDEO_PLAY_RATE',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '광고그룹 재생당 비용',
  // },
  {
    id: 27,
    filter1_depth_id: 9,
    filter2_depth_id: 18,
    filter_name: '회원가입 (1일)',
    filter_index: 'adGroup.adGroup_indicator.SIGNUP_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 회원가입 (1일)',
  },
  {
    id: 28,
    filter1_depth_id: 9,
    filter2_depth_id: 18,
    filter_name: '장바구니 보기 (1일)',
    filter_index: 'adGroup.adGroup_indicator.VIEW_CART_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 장바구니 보기 (1일)',
  },
  {
    id: 29,
    filter1_depth_id: 9,
    filter2_depth_id: 18,
    filter_name: '구매 (1일)',
    filter_index: 'adGroup.adGroup_indicator.PURCHASE_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 구매 (1일)',
  },
  {
    id: 30,
    filter1_depth_id: 9,
    filter2_depth_id: 18,
    filter_name: '회원가입 (7일)',
    filter_index: 'adGroup.adGroup_indicator.SIGNUP_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 회원가입 (7일)',
  },
  {
    id: 31,
    filter1_depth_id: 9,
    filter2_depth_id: 18,
    filter_name: '장바구니 보기 (7일)',
    filter_index: 'adGroup.adGroup_indicator.VIEW_CART_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 장바구니 보기 (7일)',
  },
  {
    id: 32,
    filter1_depth_id: 9,
    filter2_depth_id: 18,
    filter_name: '구매 (7일)',
    filter_index: 'adGroup.adGroup_indicator.PURCHASE_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '광고그룹 구매 (7일)',
  },
  {
    id: 33,
    filter1_depth_id: 10,
    filter2_depth_id: 19,
    filter_name: '비용',
    filter_index: 'creative.creative_indicator.COST',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 비용',
  },
  {
    id: 34,
    filter1_depth_id: 10,
    filter2_depth_id: 20,
    filter_name: '노출수',
    filter_index: 'creative.creative_indicator.IMPRESSION',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 노출수',
  },
  {
    id: 35,
    filter1_depth_id: 10,
    filter2_depth_id: 20,
    filter_name: '클릭수',
    filter_index: 'creative.creative_indicator.CLICK',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 클릭수',
  },
  {
    id: 36,
    filter1_depth_id: 10,
    filter2_depth_id: 20,
    filter_name: '클릭률',
    filter_index: 'creative.creative_indicator.CTR',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 클릭률',
  },
  // {
  //   id: 37,
  //   filter1_depth_id: 10,
  //   filter2_depth_id: 20,
  //   filter_name: '도달수',
  //   filter_index: 'creative.creative_indicator.REACH',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '소재 도달수',
  // },
  // {
  //   id: 38,
  //   filter1_depth_id: 10,
  //   filter2_depth_id: 20,
  //   filter_name: '재생수',
  //   filter_index: 'creative.creative_indicator.VIDEO_PLAY_3_SECONDS',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '소재 재생수',
  // },
  {
    id: 39,
    filter1_depth_id: 10,
    filter2_depth_id: 20,
    filter_name: '노출당 비용',
    filter_index: 'creative.creative_indicator.CPM',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 노출당 비용',
  },
  {
    id: 40,
    filter1_depth_id: 10,
    filter2_depth_id: 20,
    filter_name: '클릭당 비용',
    filter_index: 'creative.creative_indicator.CPC',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 클릭당 비용',
  },
  // {
  //   id: 41,
  //   filter1_depth_id: 10,
  //   filter2_depth_id: 20,
  //   filter_name: '도달당 비용',
  //   filter_index: 'creative.creative_indicator.REACH_RATE',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '소재 도달당 비용',
  // },
  // {
  //   id: 42,
  //   filter1_depth_id: 10,
  //   filter2_depth_id: 20,
  //   filter_name: '재생당 비용',
  //   filter_index: 'creative.creative_indicator.VIDEO_PLAY_RATE',
  //   inpType: 'I&P(N)&S',
  //   formatTitle: '소재 재생당 비용',
  // },
  {
    id: 43,
    filter1_depth_id: 10,
    filter2_depth_id: 21,
    filter_name: '회원가입 (1일)',
    filter_index: 'creative.creative_indicator.SIGNUP_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 회원가입 (1일)',
  },
  {
    id: 44,
    filter1_depth_id: 10,
    filter2_depth_id: 21,
    filter_name: '장바구니 보기 (1일)',
    filter_index: 'creative.creative_indicator.VIEW_CART_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 장바구니 보기 (1일)',
  },
  {
    id: 45,
    filter1_depth_id: 10,
    filter2_depth_id: 21,
    filter_name: '구매 (1일)',
    filter_index: 'creative.creative_indicator.PURCHASE_DAY_1',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 구매 (1일)',
  },
  {
    id: 46,
    filter1_depth_id: 10,
    filter2_depth_id: 21,
    filter_name: '회원가입 (7일)',
    filter_index: 'creative.creative_indicator.SIGNUP_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 회원가입 (7일)',
  },
  {
    id: 47,
    filter1_depth_id: 10,
    filter2_depth_id: 21,
    filter_name: '장바구니 보기 (7일)',
    filter_index: 'creative.creative_indicator.VIEW_CART_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 장바구니 보기 (7일)',
  },
  {
    id: 48,
    filter1_depth_id: 10,
    filter2_depth_id: 21,
    filter_name: '구매 (7일)',
    filter_index: 'creative.creative_indicator.PURCHASE_DAY_7',
    inpType: 'I&P(N)&S',
    formatTitle: '소재 구매 (7일)',
  },
];

export const checkboxListItems: Array<CheckboxListProps> = [
  {
    id: 1,
    inpId: 'check|filterCondition|onOff|ON',
    inpLabel: 'ON',
    inpValue: 'ON',
    inpType: 'S(ON/OFF)',
  },
  {
    id: 2,
    inpId: 'check|filterCondition|onOff|OFF',
    inpLabel: 'OFF',
    inpValue: 'OFF',
    inpType: 'S(ON/OFF)',
  },
  {
    id: 3,
    inpId: 'check|filter|operationStatus|READY',
    inpLabel: '집행 예정',
    inpValue: 'READY',
    inpType: 'S(CAMPAIGNSTATUS)',
  },
  {
    id: 4,
    inpId: 'check|filter|operationStatus|LIVE',
    inpLabel: '집행 중',
    inpValue: 'LIVE',
    inpType: 'S(CAMPAIGNSTATUS)',
  },
  {
    id: 5,
    inpId: 'check|filter|operationStatus|FINISHED',
    inpLabel: '집행 완료',
    inpValue: 'FINISHED',
    inpType: 'S(CAMPAIGNSTATUS)',
  },
  {
    id: 6,
    inpId: 'check|filter|operationStatus|ADMIN_STOP',
    inpLabel: '운영 불가(관리자 정지)',
    inpValue: 'ADMIN_STOP',
    inpType: 'S(CAMPAIGNSTATUS)',
  },
  // {
  //   id: 7,
  //   inpId: 'check|filter|operationStatus|SYSTEM_CONFIG_EXTERNAL_SERVICE_STOP',
  //   inpLabel: '운영 불가(연결 서비스 제한)',
  //   inpValue: 'SYSTEM_CONFIG_EXTERNAL_SERVICE_STOP',
  //   inpType: 'S(CAMPAIGNSTATUS)',
  // },
  // {
  //   id: 8,
  //   inpId: 'check|filter|operationStatus|EXCEED_DAILY_BUDGET',
  //   inpLabel: '운영 불가(예산 초과)',
  //   inpValue: 'EXCEED_DAILY_BUDGET',
  //   inpType: 'S(CAMPAIGNSTATUS)',
  // },
  // {
  //   id: 9,
  //   inpId: 'check|filter|operationStatus|ADACCOUNT_UNAVAILABLE',
  //   inpLabel: '운영 불가',
  //   inpValue: 'ADACCOUNT_UNAVAILABLE',
  //   inpType: 'S(CAMPAIGNSTATUS)',
  // },
  {
    id: 10,
    inpId: 'check|filter|operationStatus|OFF',
    inpLabel: '사용자 OFF',
    inpValue: 'OFF',
    inpType: 'S(CAMPAIGNSTATUS)',
  },
  {
    id: 11,
    inpId: 'check|filter|operationStatus|READY',
    inpLabel: '집행 예정',
    inpValue: 'READY',
    inpType: 'S(ADGROUPSTATUS)',
  },
  {
    id: 12,
    inpId: 'check|filter|operationStatus|LIVE',
    inpLabel: '집행 중',
    inpValue: 'LIVE',
    inpType: 'S(ADGROUPSTATUS)',
  },
  {
    id: 13,
    inpId: 'check|filter|operationStatus|FINISHED',
    inpLabel: '집행 완료',
    inpValue: 'FINISHED',
    inpType: 'S(ADGROUPSTATUS)',
  },
  {
    id: 14,
    inpId: 'check|filter|operationStatus|ADMIN_STOP',
    inpLabel: '운영 불가(관리자 정지)',
    inpValue: 'ADMIN_STOP',
    inpType: 'S(ADGROUPSTATUS)',
  },
  // {
  //   id: 15,
  //   inpId: 'check|filter|operationStatus|SYSTEM_CONFIG_EXTERNAL_SERVICE_STOP',
  //   inpLabel: '운영 불가(연결 서비스 제한)',
  //   inpValue: 'SYSTEM_CONFIG_EXTERNAL_SERVICE_STOP',
  //   inpType: 'S(ADGROUPSTATUS)',
  // },
  // {
  //   id: 16,
  //   inpId: 'check|filter|operationStatus|EXCEED_DAILY_BUDGET',
  //   inpLabel: '운영 불가(예산 초과)',
  //   inpValue: 'EXCEED_DAILY_BUDGET',
  //   inpType: 'S(ADGROUPSTATUS)',
  // },
  // {
  //   id: 17,
  //   inpId: 'check|filter|operationStatus|CANCELED',
  //   inpLabel: '운영 불가(계약 해지)',
  //   inpValue: 'CANCELED',
  //   inpType: 'S(ADGROUPSTATUS)',
  // },
  // {
  //   id: 18,
  //   inpId: 'check|filter|operationStatus|PAUSED',
  //   inpLabel: '운영 불가(일시 중지)',
  //   inpValue: 'PAUSED',
  //   inpType: 'S(ADGROUPSTATUS)',
  // },
  // {
  //   id: 19,
  //   inpId: 'check|filter|operationStatus|ADACCOUNT_UNAVAILABLE',
  //   inpLabel: '운영 불가',
  //   inpValue: 'ADACCOUNT_UNAVAILABLE',
  //   inpType: 'S(ADGROUPSTATUS)',
  // },
  // {
  //   id: 20,
  //   inpId: 'check|filter|operationStatus|NO_AVAILABLE_CREATIVE',
  //   inpLabel: '운영 불가(집행가능 소재없음)',
  //   inpValue: 'NO_AVAILABLE_CREATIVE',
  //   inpType: 'S(ADGROUPSTATUS)',
  // },
  {
    id: 21,
    inpId: 'check|filter|operationStatus|OFF',
    inpLabel: '사용자 OFF',
    inpValue: 'OFF',
    inpType: 'S(ADGROUPSTATUS)',
  },
  {
    id: 22,
    inpId: 'check|filter|operationStatus|OPERATING',
    inpLabel: '운영 가능',
    inpValue: 'OPERATING',
    inpType: 'S(CREATIVESTATUS)',
  },
  {
    id: 23,
    inpId: 'check|filter|operationStatus|ADMIN_STOP',
    inpLabel: '운영 불가(관리자 정지)',
    inpValue: 'ADMIN_STOP',
    inpType: 'S(CREATIVESTATUS)',
  },
  {
    id: 24,
    inpId: 'check|filter|operationStatus|UNAPPROVED',
    inpLabel: '운영 불가(심사 미승인)',
    inpValue: 'UNAPPROVED',
    inpType: 'S(CREATIVESTATUS)',
  },
  // {
  //   id: 25,
  //   inpId: 'check|filter|operationStatus|INVALID_DATE',
  //   inpLabel: '운영 불가(기간 오류)',
  //   inpValue: 'INVALID_DATE',
  //   inpType: 'S(CREATIVESTATUS)',
  // },
  // {
  //   id: 26,
  //   inpId: 'check|filter|operationStatus|SYSTEM_CONFIG_VOID',
  //   inpLabel: '운영 불가(콘텐츠 오류)',
  //   inpValue: 'SYSTEM_CONFIG_VOID',
  //   inpType: 'S(CREATIVESTATUS)',
  // },
  // {
  //   id: 27,
  //   inpId: 'check|filter|operationStatus|ADGROUP_UNAVAILABLE',
  //   inpLabel: '운영 불가',
  //   inpValue: 'ADGROUP_UNAVAILABLE',
  //   inpType: 'S(CREATIVESTATUS)',
  // },
  {
    id: 28,
    inpId: 'check|filter|operationStatus|OFF',
    inpLabel: '사용자 OFF',
    inpValue: 'OFF',
    inpType: 'S(CREATIVESTATUS)',
  },
  {
    id: 29,
    inpId: 'check|filterCondition|reviewStatus|APPROVED',
    inpLabel: '심사 승인',
    inpValue: 'APPROVED',
    inpType: 'S(CREATIVEREVIEWSTATUS)',
  },
  {
    id: 30,
    inpId: 'check|filterCondition|reviewStatus|WAITING',
    inpLabel: '심사 중',
    inpValue: 'WAITING',
    inpType: 'S(CREATIVEREVIEWSTATUS)',
  },
  {
    id: 31,
    inpId: 'check|filterCondition|reviewStatus|REJECTED',
    inpLabel: '심사 보류',
    inpValue: 'REJECTED',
    inpType: 'S(CREATIVEREVIEWSTATUS)',
  },
  // {
  //   id: 33,
  //   inpId: 'check|filterCondition|reviewStatus|MODIFICATION_WAITING',
  //   inpLabel: '수정사항 심사 중',
  //   inpValue: 'MODIFICATION_WAITING',
  //   inpType: 'S(CREATIVEREVIEWSTATUS)',
  // },
  // {
  //   id: 34,
  //   inpId: 'check|filterCondition|reviewStatus|MODIFICATION_REJECTED',
  //   inpLabel: '수정사항 심사 보류',
  //   inpValue: 'MODIFICATION_REJECTED',
  //   inpType: 'S(CREATIVEREVIEWSTATUS)',
  // },
  {
    id: 35,
    inpId: 'check|filterCondition|campaignType|DISPLAY',
    inpLabel: '디스플레이',
    inpValue: 'DISPLAY',
    inpType: 'S(CAMPAIGNTYPE)',
  },
  // {
  //   id: 36,
  //   inpId: 'check|filterCondition|campaignType|VIDEO',
  //   inpLabel: '동영상',
  //   inpValue: 'VIDEO',
  //   inpType: 'S(CAMPAIGNTYPE)',
  // },
  {
    id: 37,
    inpId: 'check|filterCondition|goal|CONVERSION',
    inpLabel: '전환',
    inpValue: 'CONVERSION',
    inpType: 'S(CAMPAIGNGOAL)',
  },
  {
    id: 38,
    inpId: 'check|filterCondition|goal|VISITING',
    inpLabel: '방문',
    inpValue: 'VISITING',
    inpType: 'S(CAMPAIGNGOAL)',
  },
  {
    id: 39,
    inpId: 'check|filterCondition|goal|REACH',
    inpLabel: '도달',
    inpValue: 'REACH',
    inpType: 'S(CAMPAIGNGOAL)',
  },
  {
    id: 40,
    inpId: 'check|filterCondition|goal|VIEW',
    inpLabel: '조회',
    inpValue: 'VIEW',
    inpType: 'S(CAMPAIGNGOAL)',
  },
  // {
  //   id: 41,
  //   inpId: 'check|filterCondition|creativeFormat|IMAGE_BANNER',
  //   inpLabel: '이미지 > 배너',
  //   inpValue: 'IMAGE_BANNER',
  //   inpType: 'S(CREATIVETYPE)',
  // },
  {
    id: 42,
    inpId: 'check|filterCondition|creativeFormat|IMAGE_NATIVE',
    inpLabel: '이미지 > 네이티브',
    inpValue: 'IMAGE_NATIVE',
    inpType: 'S(CREATIVETYPE)',
  },
  // {
  //   id: 43,
  //   inpId: 'check|filterCondition|creativeFormat|VIDEO_NATIVE',
  //   inpLabel: '동영상 > 네이티브',
  //   inpValue: 'VIDEO_NATIVE',
  //   inpType: 'S(CREATIVETYPE)',
  // },
];

export const filterSelectRangeOptions: { label: string; value: string }[] = [
  { label: '이상', value: 'GTE' },
  { label: '이하', value: 'LTE' },
  { label: '같음', value: 'EQ' },
];
